# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ebcc5b019622a6ef2f69078bc9daa8a18e77fc68e1cc44d6b013715271eead2816703dd5bf755a180a75810754cb78fc703e03c78f4118726f46bb5442d486b

test:
  secret_key_base: 262c74f3bd46325b58df385511c2702c2ea3a088cd334a9862b27daafe1bd7c003ba68dd09419a1c5bdbc3482e1c5b9409ce4af533d975934b54a987bd26b9e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
